# Generated by Django 5.1.4 on 2025-01-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_timers_background_color_timers_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timers',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='music',
        ),
    ]
