# Generated by Django 5.1.4 on 2025-01-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_timers_background_color_remove_timers_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='music',
            field=models.CharField(default='static/media/audio/1.mp3', max_length=255),
        ),
    ]
