# Generated by Django 5.1.4 on 2025-01-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_timers_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timers',
            name='music',
        ),
    ]
